services:
  app:
    build: .
    image: music-monitor:1.2.0
    container_name: Music-monitor
    ports:
      - "6696:6696"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/app/data
      - ./downloads:/app/downloads
    restart: unless-stopped
