services:
  music-monitor:
    image: music-monitor:1.1.0
    container_name: music-monitor
    restart: unless-stopped
    ports:
      - "${wizard_port:-6696}:6696"
    environment:
      - TZ=${wizard_tz:-Asia/Shanghai}
    volumes:
      - "${wizard_data_dir:-/var/apps/music-monitor/shares/data}:/app/data"
      - "${wizard_music_dir:-/vol1/1000/music}:/app/downloads"
